### ISSUE TITLE
collectd is not available to be installed

### ISSUE THREAD

**Issue by MatteoInfi** [awslabs/ecs-refarch-cloudformation#111]
Hello, I get this error from cloudformation init

```
Error occurred during build: Yum does not have collectd available for installation
ValidationError: Stack arn:aws:cloudformation:us-west-1:370710806300:stack/server-hosting-rust-ecs-cluster-dev/f81f8640-b48f-11ea-8726-028e68dfd5f1 is in UPDATE_COMPLETE state and cannot be signaled
Created symlink from /etc/systemd/system/multi-user.target.wants/hibagent.service to /usr/lib/systemd/system/hibagent.service.
ci-info: no authorized ssh keys fingerprints found for user ec2-user.
Cloud-init v. 19.3-3.amzn2 finished at Mon, 22 Jun 2020 14:15:16 +0000. Datasource DataSourceEc2.  Up 199.72 seconds
sh-4.2$ cat /var/log/cfn-init.log
2020-06-22 14:15:11,573 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-west-1.amazonaws.com
2020-06-22 14:15:11,574 [DEBUG] Describing resource ECSLaunchConfiguration in stack server-hosting-rust-ecs-cluster-dev
2020-06-22 14:15:11,638 [INFO] -----------------------Starting build-----------------------
2020-06-22 14:15:11,638 [DEBUG] Not setting a reboot trigger as scheduling support is not available
2020-06-22 14:15:11,639 [INFO] Running configSets: default
2020-06-22 14:15:11,639 [INFO] Running configSet default
2020-06-22 14:15:11,640 [INFO] Running config config
2020-06-22 14:15:15,804 [ERROR] collectd is not available to be installed
2020-06-22 14:15:15,804 [ERROR] Error encountered during build of config: Yum does not have collectd available for installation
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 229, in build
    changes['packages'][manager] = CloudFormationCarpenter._packageTools[manager]().apply(packages, self._auth_config)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/rpm_tools.py", line 74, in apply
    raise ToolError("Yum does not have %s available for installation" % pkg_spec)
ToolError: Yum does not have collectd available for installation
2020-06-22 14:15:15,805 [ERROR] -----------------------BUILD FAILED!------------------------
2020-06-22 14:15:15,805 [ERROR] Unhandled exception during build: Yum does not have collectd available for installation
Traceback (most recent call last):
  File "/opt/aws/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 229, in build
    changes['packages'][manager] = CloudFormationCarpenter._packageTools[manager]().apply(packages, self._auth_config)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/rpm_tools.py", line 74, in apply
    raise ToolError("Yum does not have %s available for installation" % pkg_spec)
ToolError: Yum does not have collectd available for installation
2020-06-22 14:15:15,964 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-west-1.amazonaws.com
2020-06-22 14:15:15,964 [DEBUG] Signaling resource ECSAutoScalingGroup in stack server-hosting-rust-ecs-cluster-dev with unique ID i-022948f642aaaa08f and status FAILURE
```

**Comment by MatteoInfi** [comment]
Solved by adding this line to the userData:

```
yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
```

as in this issue: #103
